```{r include = FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Lecture 1b: Visualization

[link to slides](https://archive.math.wsu.edu/faculty/xchen/stat437/LectureNotes1b.html#/static-visualization)

Visualizing High Dimensional Data is Difficult. Hopf Fibration [link](https://en.wikipedia.org/wiki/Hopf_fibration)

Two Paradigms: 1. Static Visualization: Snapshot of a data set(non-interactive) 1. 
Dynamic Visualization: A sequence of snapshots of data that a user can interact with (interactive)

Static: An example is a fixed generated graph. Dynamic: An example is a dashboard 
with filters or slicers. Or an animation.

#### Static Packages
There are several packages for static visualizations, Such as ggplot2. The Package, 
igraph, creates graphs. ggdendro creates dendrograms(like tree of life) and tree 
diagrams, and ggmap which visualizes dataframes over maps.

#### Dynamic Packages
ploty, for dynamic data frame visualization using dashboards, and gganimate which
creates animations.

### ggplot2
