---
title: "Lec4 Notes"
author: "John Salmon"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Given the right scenario, frequency will converge to expected value.
We use this principle to estimate the accuracy of classification.

0-1 loss is a measure on classification performance its counting the off diagonal entries in a confusion matrix

in the long run we want to minimize the expected loss. 

If the true label $k$ is the same as the estimated label $\hat{G}$ then the 0-1 loss value is 0
if the true label and estimated label are different then the loss value is 1

$L(G(x), \hat{G}(X))$ The G(x) value is random in the bayesean framework (but in frequentist its deterministic) in general $\hat{G}(x)$ is also random every time.

The minimizer, fortunately to minimize the expected 0-1 loss we can just minimize everything after the $E_X$

Bayesans make decisions based on maximum post posterior probability.

Deep learning at a simple level follows a similar principle where once you minimize entropy loss you basically end up minimizing 0-1 loss anyway.

0-1 loss doesn't always work when the structure of loss is not symmetric.
The threshold of 0.5 doesn't always work if there is an imbalance in the consequences of false negative vs false positive

if you change the threshold you likely aren't using 0-1 loss anymore.

When using bayes classifier multi-class the process is mostly the same, except that it has different thresholds for class assignment based on posterior probability

In classification there are many methods, but the Bayes method is the peak

## 4A
#### k-nearest neighbor (kNN)

Nearest Neighbor Methods
- a class of classification methods and belong to the family of supervised learning methods, where methods are trained from observations that have class labels
- classify a new observation to a class using features of its neighboring observations
- can be regarded as estimating the unknown conditional probabilities that are used by the Bayes classifier.

In our case we always measure a fixed number of features and worth with that exact number, in the real world this is not always the case.

KNN algorithm:
1. Specify a positive integer k as the number of neighbors
1. Let $K_N(X)$ be the neighborhood of x consisting of $k$ points $x_i$. Compute the average label as $\bar{Y}$.
1. Specify a threshold $\beta\in(0,1)$ and estimate the class label of $x$ as $\hat{Y} = 1 \text{ if } \bar{Y}(x) > \beta \text{ or } \bar{Y}(x) = 0 \text{ otherwise.}$

See time series: moving average operator ~ convolution ~ blur imaging

Your neighborhood changes shape as you move it no matter how dense or sparsely populated your observations are.
You don't always have to use $\frac{1}{K}$ for the weights of your observations. Sometimes it can be worth weighting them by distance from the point you are examining.

The average label will be 0 or 1 when either a. all neighbors are 0 or 1 b. there is only 1 neighbor.

in the Bayesian scheme you set $\beta = \frac{1}{2}$ and use the $\frac{1}{k}$ to approximate Bayes rule.
The average function is an unbiased estimator of $Pr(Y_i = 1)$, in other words the average is estimating the probability that the class label is 1.

In the real world, all we have is frequency. We never have a real idea of what the actual probabilities are going to be. Take weather prediction, we don't know when its going to rain but we know the past frequency of rain.

A kNN method needs:
- a neighborhood size $k$
- a measure of whether two observations are "close"
- a threshold on the "average label" to make a decision.
kNN is non-parametric, it does not assume a distribution for the observations.
Unless otherwise noted, Euclidean distance will be used to measure how close the observations are and when there are 2 classes the threshold on the average label will be 0.5

when charting the decision boundary you bound the chart based on the maximum and minimum values of the features of your data.

Classifying observations gets easier as you move away from the decision boundary.
Often there are 3 regions that are identified, High performance, Low performance, and No performance where performance lowers as you get closer and closer to the decision boundary.

2 class classification problem the decision boundary is ${x \in \mathscr{X}: \hat{y}(x) = \frac{1}{2} \text{ where } \hat{y} = \frac{1}{k}\sum^{}_{x_i \in n(x)}y_i}$

As you increase K in kNN the decision boundary will become smoother. 

Study should be Replicate-able(?), Random, and Homogeneous. 

One of the most common error measuring types is 0-1 loss. 

The training error is going to be an accurate estimation of the expected 0-1 loss if you have numerous quality observations. 

#### Training error and testing error discussion

Issues with data splitting
1. smaller sample size for training.
1. how do you split the training set

It may not be correct to assume that you can use the training error in order to conclude something about the test error.

Regression Heading paper - might say something about how to skip finding test error in specific circumstances, there is not a general solution.

$\text{logit}(E(Y(X=x))) = f(x)$ transformed into

John D. Storey statistical genomics lab.

Perceptron - simplest neural network in 1960's
with multi-layer perceptrons the training error can be close to 0 and test erroor can also be close to 0. However they were not able to explain it. 

What is the relationship between training error and test error. In the modern era, there is no relationship, when training error is always 0 the test error will just be close to 0. In a modern philosophy the training error will always be 0. As models get larger and larger, the training error begins to say less and less about the testing error.

Fit without fear paradigm.

Why is the training error of a 1-nearest neighbor always 0.

Crossvalidation for kNN often underestimates the test error which means you are overconfident in the accuracy of your model.
In the real world, we want to minimize test error, however we don't know the truth in reality so we have to estimate the test error.

When using Cross-validation to find the optimal value of k, the sample size needs to be large otherwise there will not be sufficient evidence to select the proper value for K.

kNN breaks down as dimensionality increases because there are more "directions" for data to be distributed. This causes the probability of finding an observation in a given neighborhood size to trend to 0. This is the `Curse of Dimensionality for Classification` the more features/dimensions there are the more space there is for observations to lie in. 

If you chose how the data is generated or sampled you can alleviate this problem because you can create regions where the concentration of observations is high enugh that you avid the 0 probability.


